version: '3.1'
services:
  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/tmp/db:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=collector
      - PGDATA=/var/lib/postgresql/data/pgdata
